# ----------------------------------------------------------
# THEME COLORS: Nord (dark)
# ----------------------------------------------------------
set -g status-style "bg=#2E3440,fg=#D8DEE9"

# left: PREFIX badge --> session --> current pane path
set -g status-left "#{?client_prefix,#[bg=#EBCB8B fg=#2E3440 bold]  PREFIX  #[bg=#2E3440 fg=#EBCB8B],#[bg=#88C0D0 fg=#2E3440 bold] 󰎤 #S #[bg=#2E3440 fg=#88C0D0]}#[bg=#3B4252,fg=#2E3440]#[bg=#3B4252,fg=#81A1C1]"

# right: user, hostname, time && date
set -g status-right "#{?#{==:#{pane_current_command},ssh},󰒍 server,󰉋 #{b:pane_current_path}} #[bg=#2E3440,fg=#3B4252] #[fg=#4C566A]│ #[fg=#A3BE8C]󰀄 #{?#{==:#{pane_current_command},ssh},#{?#{@ssh_user},#{@ssh_user},…},#(whoami)} #[fg=#4C566A]│ #[fg=#81A1C1] 󰣚 #{?#{==:#{pane_current_command},ssh},#{?#{@ssh_host},#{@ssh_host},…},#H} #[fg=#4C566A]"

# windows: zoom icon appears automatically on prefix+z
set -g window-status-format " #[fg=#4C566A]#I #[fg=#4C566A]#W "
set -g window-status-current-format "#[bg=#3B4252,fg=#88C0D0,bold] #I #[fg=#ECEFF4]#W#{?window_zoomed_flag, #[fg=#D08770]󰍉 ,} "

# :: pane borders ::
set -g pane-border-style "fg=#434C5E"
set -g pane-active-border-style "fg=#88C0D0"

# :: messages ::
set -g message-style "bg=#3B4252,fg=#EBCB8B"
set -g message-command-style "bg=#3B4252,fg=#88C0D0"

# :: copy mode ::
set -g mode-style "bg=#434C5E,fg=#ECEFF4"

# :: dual status bar spacing fill ::
set -g status-format[0] '#[bg=#2e3440,fill=#2e3440]#[align=centre] '
