# vim:ft=kitty

## name: Aquarium Light
## license: MIT
## author: ragdoll2iguess
## upstream: https://github.com/FrenzyExists/aquarium-vim/raw/develop/extras/kitty_aquarium_light.conf
## blurb: A simple vibrant dark theme Kitty terminal.
## Old BG -> #E6E6F1  #E1E3F2

foreground             #2E3440
background             #E5E9F0
selection_foreground   #2E3440
selection_background   #D8DEE9
url_color              #5E81AC

cursor                 #2E3440
cursor_text_color      #E5E9F0

# black
color0                 #3B4252
color8                 #4C566A

# red
color1                 #BF616A
color9                 #BF616A

# green
color2                 #A3BE8C
color10                #A3BE8C

# yellow
color3                 #EBCB8B
color11                #EBCB8B

# blue
color4                 #5E81AC
color12                #81A1C1

# magenta
color5                 #B48EAD
color13                #B48EAD

# cyan
color6                 #88C0D0
color14                #8FBCBB

# white
color7                 #D8DEE9
color15                #ECEFF4

# tabs / borders
active_tab_foreground   #E5E9F0
active_tab_background   #5E81AC
inactive_tab_foreground #4C566A
inactive_tab_background #D8DEE9
active_border_color     #5E81AC
inactive_border_color   #D8DEE9
